version: '3'

services:
  app:
    image: spring-boot-docker
    build:
      context: .
    container_name: spring-boot-app
    expose: 
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:  
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/drivingschool
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=drivingschool
    restart: 
      unless-stopped 
    